services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - mysql
      - pg
    networks:
        - cnetwork

  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./nestjs:/home/app
    command: ["npm", "run", "start:dev"]
    networks:
        - cnetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
       - cnetwork

  php:
    image: webdevops/php-apache-dev:8.2
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    networks:
        - cnetwork

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
        - cnetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
        - cnetwork

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=kpg:5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak_password
      - KEYCLOAK_HTTP_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: ["start-dev"]
    networks:
      cnetwork:
        ipv4_address: 192.168.9.100

volumes:
  pg-data:
  mysql-data:
  keycloak-data:

networks:
  cnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.9.0/24